name: 'Setup pnpm'
description: 'Composite action to setup node, pnpm, caching, and private registry access in pnpm repositories'
inputs:
  npm-token:
    required: true
    description: The npm token used to grant registry access. Pass a token with publish permissions if needed.
runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda #v4.1.0
      with:
        run_install: false
    - name: Setup Node.js
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f #v6.1.0
      with:
        node-version-file: .nvmrc
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
    - name: Allow read access to private registry
      shell: bash
      run: echo "//registry.npmjs.org/:_authToken=${{ inputs.npm-token }}" > ~/.npmrc
author: 'ExodusMovement'
branding:
  icon: 'activity'
  color: 'gray-dark'
