name: 'Dependency Review'
description: 'Check dependencies for vulnerabilities and licenses'
runs:
  using: 'composite'
  steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4.0.0
      with:
        fetch-depth: 2
    - name: Get HEAD~1 sha
      id: rev-parse
      shell: bash
      run: echo "sha=$(git rev-parse HEAD~1)" >> "$GITHUB_OUTPUT"
    - name: 'Dependency Review'
      uses: actions/dependency-review-action@9129d7d40b8c12c1ed0f60400d00c92d437adcce # v4
      with:
        config-file: './dependency-review/config.yml'
