fail-on-severity: high
comment-summary-in-pr: on-failure
# these are only used for event types other than pull_request and pull_request_target.
base-ref: ${{ steps.rev-parse.outputs.sha }}
head-ref: ${{ github.sha }}
allow-licenses: 
  - 'MIT'
  - 'Apache-2.0'
  - 'MPL-2.0'
  - 'ISC'
  - 'BSD-2-Clause'
  - 'BSD-3-Clause'
  - 'Unlicense'
  - 'CC0-1.0'
  - 'CC-BY-3.0'
  - 'WTFPL'
  - '0BSD'
  - 'AFL-2.1'
allow-dependencies-licenses:
- '@exodus/exchange-monitors'
- '@exodus/exchange-pair-generator'
- '@exodus/fusion'
- '@exodus/module'
- '@exodus/networking-browser'
- '@exodus/networking-common'
- '@exodus/networking-mobile'
- '@exodus/networking-node'
- '@exodus/networking-spec'
- '@exodus/safe-report'
- '@exodus/wallet-compatibility-modes'
- '@exodus/analytics-validation'
- '@exodus/atom-tests'
- '@exodus/atoms'
- '@exodus/dayjs'
- '@exodus/dependency-injection'
- '@exodus/dependency-preprocessors'
- '@exodus/eslint-plugin-ban-flow'
- '@exodus/eslint-plugin-basic-utils'
- '@exodus/eslint-plugin-hydra'
- '@exodus/eslint-plugin-i18n'
- '@exodus/eslint-plugin-package'
- '@exodus/eslint-plugin-restricted-imports'
- '@exodus/exchange-client-providers'
- '@exodus/exodus-exchange-client'
- '@exodus/exodus-pricing-client'
- '@exodus/fiat-client'
- '@exodus/fiat-currencies'
- '@exodus/formatting'
- '@exodus/fusion-atoms'
- '@exodus/fusion-merge'
- '@exodus/hw-common'
- '@exodus/i18n'
- '@exodus/i18n-swc'
- '@exodus/key-identifier-provider'
- '@exodus/key-ids'
- '@exodus/keychain-atoms'
- '@exodus/live-chat-utils'
- '@exodus/logger'
- '@exodus/lokalise'
- '@exodus/mock-fetch'
- '@exodus/multi-account-redux'
- '@exodus/react-hooks'
- '@exodus/redux-dependency-injection'
- '@exodus/retry'
- '@exodus/segment-metrics'
- '@exodus/send-validation'
- '@exodus/sentry-client'
- '@exodus/transform-storage'
- '@exodus/yarn-classic-downgrade'
- '@exodus/ab-testing'
- '@exodus/activity-txs'
- '@exodus/address-book'
- '@exodus/address-cache'
- '@exodus/address-provider'
- '@exodus/analytics'
- '@exodus/announcements'
- '@exodus/app-process-mobile'
- '@exodus/apy-rates'
- '@exodus/assets-feature'
- '@exodus/auth-mobile'
- '@exodus/available-assets'
- '@exodus/balances'
- '@exodus/beta-access'
- '@exodus/blockchain-metadata'
- '@exodus/call-detection'
- '@exodus/connected-origins'
- '@exodus/crypto-news-monitor'
- '@exodus/device-id'
- '@exodus/enabled-assets'
- '@exodus/event-log'
- '@exodus/exchange'
- '@exodus/export-transactions'
- '@exodus/favorite-assets'
- '@exodus/feature-flags'
- '@exodus/fee-data-monitors'
- '@exodus/fiat-balances'
- '@exodus/fiat-ramp'
- '@exodus/fiat-rate-converter'
- '@exodus/filesystem'
- '@exodus/geolocation'
- '@exodus/historical-balances'
- '@exodus/historical-fiat-balances-chart'
- '@exodus/hw-ledger'
- '@exodus/kyc'
- '@exodus/local-seed-backups'
- '@exodus/locale'
- '@exodus/market-history'
- '@exodus/nfts'
- '@exodus/optimistic-balances'
- '@exodus/orders'
- '@exodus/personal-notes'
- '@exodus/post-restore-modal'
- '@exodus/pricing'
- '@exodus/profile'
- '@exodus/public-key-provider'
- '@exodus/public-key-store'
- '@exodus/rates-monitor'
- '@exodus/referrals'
- '@exodus/remote-config'
- '@exodus/restore-progress-tracker'
- '@exodus/risk-metrics'
- '@exodus/sanctions'
- '@exodus/seedless'
- '@exodus/startup-counter'
- '@exodus/sync-time'
- '@exodus/synced-balances'
- '@exodus/top-movers-monitor'
- '@exodus/trusted-unverified-tokens'
- '@exodus/tx-acceleration'
- '@exodus/tx-log-monitors'
- '@exodus/tx-notifications'
- '@exodus/tx-signer'
- '@exodus/ui-config'
- '@exodus/wallet'
- '@exodus/wallet-accounts'
- '@exodus/fetch-factory'
- '@exodus/fusion-local'
- '@exodus/keystore-mobile'
- '@exodus/platform-info'
- '@exodus/storage-encrypted'
- '@exodus/storage-enhancers'
- '@exodus/storage-icons-browser'
- '@exodus/storage-icons-mobile'
- '@exodus/storage-interface'
- '@exodus/storage-level'
- '@exodus/storage-memory'
- '@exodus/storage-mobile'
- '@exodus/storage-seco'
- '@exodus/storage-seed'
- '@exodus/storage-spec'
- '@exodus/storage-unsafe-desktop'
- '@exodus/argo'
- '@exodus/headless'
