name: 'Setup yarn berry'
description: 'Composite action to setup node, yarn caching, and private registry access in yarn berry repositories'
inputs:
  npm-token:
    required: true
    description: The npm token used to grant registry access. Pass a token with publish permissions if needed.
runs:
  using: 'composite'

  steps:
    - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f #v6.1.0
      # this action has an option to restore cached dependencies,
      # but it only restores the cache when the lockfile is identical (so a no-no for our purposes)
      with:
        node-version-file: .nvmrc
    - name: Allow read access to private registry
      shell: bash
      run: |
        yarn config set --home 'npmRegistries["//registry.npmjs.org/"].npmAuthToken' "${{ inputs.npm-token }}"
        echo "//registry.npmjs.org/:_authToken=${{ inputs.npm-token }}" > ~/.npmrc
    - name: Restore yarn cache
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb #v5.0.1
      with:
        save-always: true
        path: |
          .yarn/cache
          .yarn/install-state.gz
          **/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
author: 'ExodusMovement'
branding:
  icon: 'activity'
  color: 'gray-dark'
