name: 'Setup yarn'
description: 'Composite action to setup node, yarn caching, and private registry access in yarn classic repositories'
inputs:
  npm-token:
    required: true
    description: The npm token used to grant registry access. Pass a token with publish permissions if needed.
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      # this action has an option to restore cached dependencies,
      # but it only restores the cache when the lockfile is identical (so a no-no for our purposes)
      with:
        node-version-file: .nvmrc
    - name: Grant access to private registry
      shell: bash
      run: echo "//registry.npmjs.org/:_authToken=${{ inputs.npm-token }}" > ~/.npmrc
    - name: Restore node_modules
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          src/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        # if we don't have a direct cache hit, this restore key will be partially matched against available caches,
        # hence restoring the latest previous cache
        restore-keys: ${{ runner.os }}-yarn-
author: 'ExodusMovement'
branding:
  icon: 'activity'
  color: 'gray-dark'
