name: 'Setup lerna'
description: |
  Composite action to setup node, yarn berry & nx caching, and private registry access in lerna monorepos.
  The nx cache directory is by default assumed under .cache/nx.
inputs:
  nx-cache-path:
    description: Path to the nx cache directory
    default: .cache/nx
  disable-nx-cache:
    description: Disables nx-cache when set to 'yes'
    default: no
  npm-token:
    required: true
    description: The npm token used to grant registry access. Pass a token with publish permissions if needed.
runs:
  using: 'composite'
  steps:
    - uses: ExodusMovement/actions/setup/yarn-berry@daef8a0f88e1382b1db1fc4fb5d3e70a4b6ac09d
      with:
        npm-token: ${{ inputs.npm-token }}
    - name: Restore nx cache
      if: inputs.disable-nx-cache == 'no'
      uses: actions/cache@v4
      with:
        save-always: true
        path: ${{ inputs.nx-cache-path }}
        key: nx-operations-cache-${{github.job}}-${{github.sha}}
        restore-keys: |
          nx-operations-cache-${{github.job}}-

author: 'ExodusMovement'
branding:
  icon: 'activity'
  color: 'gray-dark'
