name: 'Setup lerna'
description: |
  Composite action to setup node, yarn berry & nx caching, and private registry access in lerna monorepos.
  The nx cache directory is by default assumed under .cache/nx.
inputs:
  nx-cache-path:
    description: Path to the nx cache directory
    default: .cache/nx
  disable-nx-cache:
    description: Disables nx-cache when set to 'yes'
    default: no
  npm-token:
    required: true
    description: The npm token used to grant registry access. Pass a token with publish permissions if needed.
runs:
  using: 'composite'
  steps:
    - uses: ExodusMovement/actions/setup/yarn-berry@80a106ad159450be7e065a35030bd5732714f6f8
      with:
        npm-token: ${{ inputs.npm-token }}
    - name: Restore nx cache
      if: inputs.disable-nx-cache == 'no'
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb #v5.0.1
      with:
        save-always: true
        path: ${{ inputs.nx-cache-path }}
        key: nx-operations-cache-${{github.job}}-${{github.sha}}
        restore-keys: |
          nx-operations-cache-${{github.job}}-

author: 'ExodusMovement'
branding:
  icon: 'activity'
  color: 'gray-dark'
