name: 'Setup lerna (pnpm)'
description: |
  Composite action to setup node, pnpm & nx caching, and private registry access in lerna monorepos using pnpm.
  The nx cache directory is by default assumed under .cache/nx.
inputs:
  nx-cache-path:
    description: Path to the nx cache directory
    default: .cache/nx
  disable-nx-cache:
    description: Disables nx-cache when set to 'yes'
    default: no
  npm-token:
    required: true
    description: The npm token used to grant registry access. Pass a token with publish permissions if needed.
runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda #v4.1.0
      with:
        run_install: false
    - name: Setup Node.js
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f #v6.1.0
      with:
        node-version-file: .nvmrc
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
    - name: Export NODE_AUTH_TOKEN
      shell: bash
      run: echo "NODE_AUTH_TOKEN=${{ inputs.npm-token }}" >> $GITHUB_ENV
    - name: Restore nx cache
      if: inputs.disable-nx-cache == 'no'
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb #v5.0.1
      with:
        save-always: true
        path: ${{ inputs.nx-cache-path }}
        key: nx-operations-cache-${{github.job}}-${{github.sha}}
        restore-keys: |
          nx-operations-cache-${{github.job}}-

author: 'ExodusMovement'
branding:
  icon: 'activity'
  color: 'gray-dark'
