name: Test setup/lerna
on:
  push:
    branches: [master]
    paths: [setup/lerna/**]
  pull_request:
    types: [opened, synchronize]
    paths: [setup/lerna/**]

jobs:
  integration-test:
    name: Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test repository
        uses: actions/checkout@v3
        with:
          repository: ExodusMovement/lerna-test
          ref: master
          token: ${{ secrets.GH_AUTOMATION_PAT }}
      - uses: actions/checkout@v3
        with:
          path: actions
      - uses: ./actions/setup/lerna
        with:
          npm-token: ${{ NPM_PUBLISH_TOKEN }}
      - uses: ExodusMovement/lerna-release-action/publish@master
        with:
          github-token: ${{ secrets.GH_AUTOMATION_PAT }}
